----EXEC [ETL].[dbo].[RESET_ALL_LOGS]
----EXEC [dbo].[PROC_TRUNCATE_RAW_AJK_PESERTA]

--SELECT * FROM ETL.[dbo].[APPLICATION_EXECUTION_INSTANCE]
--SELECT * FROM ETL.[dbo].[TASK_EXECUTION_INSTANCE] ORDER BY TASK_EXECUTION_INSTANCE_ID DESC
--SELECT TOP 4 * FROM [ajk].[peserta_insert] ORDER BY peserta_ID DESC
--SELECT TOP 3 * FROM [ajk].[peserta_update] ORDER BY peserta_ID DESC
--SELECT TOP 3 * FROM [ajk].[peserta_delete] ORDER BY peserta_ID DESC
--SELECT TOP 4 'INITAL' AS ACTION2, * FROM [ajk].[peserta_stage] WHERE ACTION = 0 ORDER BY peserta_ID DESC
SELECT TOP 4 'INSERT' AS ACTION2, * FROM [ajk].[peserta_stage] WHERE ACTION = 1 ORDER BY peserta_ID DESC
SELECT TOP 4 'UPDATE' AS ACTION2, * FROM [ajk].[peserta_stage] WHERE ACTION = 2 ORDER BY peserta_ID DESC
SELECT TOP 4 'DELETE' AS ACTION2, * FROM [ajk].[peserta_stage] WHERE ACTION = 3 ORDER BY peserta_ID DESC
SELECT TOP 4 CASE WHEN ACTION = 0 THEN 'INITIAL' WHEN ACTION = 1 THEN 'INSERT' WHEN ACTION = 2 THEN 'UPDATE' WHEN ACTION = 3 THEN 'DELETE' END AS ACTION2, * FROM [ajk].[peserta] ORDER BY peserta_ID DESC
--SELECT TOP 4 ERROR_DESCRIPTION FROM [ETL].[log].[TASK_EXECUTION_ERROR] ORDER BY TASK_ERROR_ID DESC
--SELECT * FROM [ETL].[log].[APPLICATION_EXECUTION_ERROR]
--SELECT * FROM [ETL].[log].[TASK_EXECUTION_VARIABLE_LOG]